; Simple variables
[section_1]
app.settings.variable_bool_0 = 1
app.settings.variable_bool_1 = false
app.settings.variable_int = 512
app.settings.variable_float = -1.512

; Nested configuration
[section_2]
app.settings.window.width = 1280
app.settings.window.height = 720
app.settings.window.fullscreen = true

app.program1.enabled = 1
app.program1.ratio = 1.0
app.program1.threshold = -0.75f

network.proxy.enabled = false
network.proxy.host = localhost
network.proxy.port = 8080